# Generated by Django 5.2.5 on 2025-09-30 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnahub', '0002_seed_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['author'], name='qnahub_answ_author__ee80b9_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['timestamp'], name='qnahub_answ_timesta_5ebf30_idx'),
        ),
    ]
